Updater: Suppress PROVIDED_RUNTIME_TOO_LOW for NetworkUpdate
packages/apps/Updater/app/src/main/java/org/lineageos/updater/data/source/network/NetworkUpdate.kt:12:1: error: your current kotlinx.serialization core version is 2.2
.0, while current Kotlin compiler plugin unknown requires at least 1.0-M1-SNAPSHOT. Please update your kotlinx.serialization runtime dependency.
@ Serializable
^^^^^^^^^^^^^
packages/apps/Updater/app/src/main/java/org/lineageos/updater/data/source/network/NetworkUpdate.kt:23:1: error: your current kotlinx.serialization core version is 2.2
.0, while current Kotlin compiler plugin unknown requires at least 1.0-M1-SNAPSHOT. Please update your kotlinx.serialization runtime dependency.
@ Serializable

Change-Id: I98cd88d7143330bfc697e50ce2dc2bee063998e9